version: "3.8"

services:

  frontend:
    build: ./frontend
    ports: 
      - 4200:80

  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      MONGO_URI: ${MONGO_URI}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL}