version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      # AUTH0_CLIENT_SECRET: ""

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - schuetties-home:/data/db
    restart: always
    networks:
      - default
    container_name: mongodb

volumes:
  schuetties-home: