name: Frontend

on: [push]

jobs:

  Build_test_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Install Dependencies
        run: |
          cd ~/frontend
          npm ci
          npm install -g @angular/cli

      - name: Build
        run: cd ~/frontend && npm run build:prod --output-path=dist 

      - name: Test
        run: cd ~/frontend && npm run test:prod
  
      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          image-name: schuett-webapp-frontend
          additional-image-tags: ${{ github.run_id }}



